baseURL = "https://most323.github.io/officialWebSite"
languageCode = "en-us"
title = "Jinho Lee"
publishDir = "docs"
theme = "resume"

[params]
    firstName = "Jinho"
    lastName = "Lee"
    address = "SungKyunKwan University(SKKU), South Korea"
    contactNote = "Dev Tools Engineer"
    profileImage = "img/TechChat.png"
    email = "leejinho610 (at) gmail (dot) com"
    description = "Software Developer"
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true

    showQr = true

#[[params.handles]]
   # name = "LinkedIn"
   # link = "https://www.linkedin.com/in/edwardwebb/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/most323/"

#[[params.handles]]
#    name = "Bitbucket"
#    link = "https://bitbucket.org/eddiewebb/"

#[[params.handles]]
#    name = "Stack Overflow"
#    link = "https://stackoverflow.com/users/story/82880"
#    icon = "stack-overflow"

#[[params.handles]]
#    name = "Keybase"
#    link = "https://keybase.io/edwardawebb"
#    icon = "key"

[params.google.analytics]
    trackerID = "XX-123446-01"
